# Generated by Django 6.1.1 on 2026-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
                ('hosted_url', models.URLField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('lever', 'Lever'), ('greenhouse', 'Greenhouse')], default='manual', max_length=255)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
