# Generated by Django 6.1.1 on 2026-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='apply_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='hosted_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('lever', 'Lever'), ('greenhouse', 'Greenhouse')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='unique_external_internship'),
        ),
    ]
