# Generated by Django 6.1.1 on 2026-09-19 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_internship_apply_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('interview', 'Interview'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('internship_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.internship')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('applicant', 'internship_applied'), name='user_unique_internship')],
            },
        ),
    ]
